# Generated by Django 4.1.7 on 2023-03-31 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название станции')),
                ('url_free', models.CharField(blank=True, max_length=255, null=True, verbose_name='URL потока для бесплатной версии')),
                ('url_paid', models.CharField(blank=True, max_length=255, null=True, verbose_name='URL потока для платной версии')),
                ('order', models.PositiveIntegerField(null=True, verbose_name='Порядковый номер')),
                ('paid', models.BooleanField(default=False, verbose_name='Платная станция')),
                ('active', models.BooleanField(default=True, help_text='Если станция неактивна, она не будет возвращаться в запросе', verbose_name='Активная станция')),
                ('miniature', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Изображение миниатюры')),
                ('bg_image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Изображение для фона')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Обложка')),
                ('buy_trek', models.FileField(blank=True, null=True, upload_to='files/', verbose_name='Трек перед покупкой')),
                ('start_trek', models.FileField(blank=True, null=True, upload_to='files/', verbose_name='Tрек при первом запуске')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('order',),
            },
        ),
    ]
